// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChzfC7K0rBrmwbrsJeYvxNUCXK9yCQ0M8',
    appId: '1:486968164701:web:4025dc4679ead36c30a8b4',
    messagingSenderId: '486968164701',
    projectId: 'user-authenication-c369a',
    authDomain: 'user-authenication-c369a.firebaseapp.com',
    storageBucket: 'user-authenication-c369a.firebasestorage.app',
    measurementId: 'G-77R7QY58N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOwqs_WUMZ2Hz1gkaAUuq-VzLrdW3LkR0',
    appId: '1:486968164701:android:1b45862c3b32765230a8b4',
    messagingSenderId: '486968164701',
    projectId: 'user-authenication-c369a',
    storageBucket: 'user-authenication-c369a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHVSztv5HxdD1JXM-yqdKiJX0gON3MCE4',
    appId: '1:486968164701:ios:c22e5ec3eb0b6e0330a8b4',
    messagingSenderId: '486968164701',
    projectId: 'user-authenication-c369a',
    storageBucket: 'user-authenication-c369a.firebasestorage.app',
    iosClientId: '486968164701-40ajqf72blk0q4djv66rkumd8m4ctgpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.userAuthenication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChzfC7K0rBrmwbrsJeYvxNUCXK9yCQ0M8',
    appId: '1:486968164701:web:cdbbc19a1533e1a230a8b4',
    messagingSenderId: '486968164701',
    projectId: 'user-authenication-c369a',
    authDomain: 'user-authenication-c369a.firebaseapp.com',
    storageBucket: 'user-authenication-c369a.firebasestorage.app',
    measurementId: 'G-WECK7TJYMH',
  );
}
